{% set name = "xeus_octave" %}
{% set version = "0.0.2dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/rapgenic/xeus-octave.git
  git_rev: 373d79385c175f19900e099a53215c9e148caabc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - ninja
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - octave
    - cppzmq >=4.4.1,<5
    - zeromq
    - xtl >=0.7.0,<0.8
    - xeus >=2.0.0,<3.0
    - nlohmann_json >=3.9.1,<4.0
    - xorg-libxfixes  # [linux]
    - glfw
    - libpng
  run:
    - glfw
    - octave

test:
  commands:
    - test -f ${PREFIX}/bin/xoctave  # [unix]

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'xeus kernel for octave'

  description: |
    xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools octave.

extra:
  recipe-maintainers:
    - rapgenic
    - marimeireles
    - SylvainCorlay
