{% set name = "xeus_octave" %}
{% set version = "0.0.2dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapgenic/xeus-octave/archive/373d79385c175f19900e099a53215c9e148caabc.zip
  sha256: 0320fddf6b8e1ae4d23a5489e6b1d609d37bab7b2641fa16c6ae92ace5c0e759

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - ninja
    - pkg-config  # [osx]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - nlohmann_json >=3.9.1,<4.0
    - octave
    - xeus >=1.0,<2.0
    - xproperty
    - xorg-libxfixes  # [linux]
    - glfw
    - libpng
  run:
    - glfw
    - octave

test:
  commands:
    - test -f ${PREFIX}/bin/xeus-octave  # [unix]

about:
  home: https://github.com/rapgenic/xeus-octave
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: 'xeus kernel for octave'

  description: |
    xeus kernel for the mathematics-oriented syntax with built-in
    2D/3D plotting and visualization tools octave.

extra:
  recipe-maintainers:
    - rapgenic
    - marimeireles
    - SylvainCorlay
